spring:
  profiles:
    active:

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
               

endpoints:
  info:
    enabled: true
  health:
    enabled: true

logging:
  level:
    com.warpaint: INFO

---

spring:
  profiles: dev

  jpa:
    show-sql: true

logging:
  level:
    com.warpaint: DEBUG

---

spring:
  profiles: test
  
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;IGNORECASE=TRUE
    username: SA
    password:
  
---

spring:
  profiles: IT
